##
## Makefile for test in /home/ghikh_r/rendu/CPE_2015_Pushswap
## 
## Made by Raphael Ghikh
## Login   <ghikh_r@epitech.net>
## 
## Started on  Sat Nov 21 21:01:14 2015 Raphael Ghikh
## Last update Sun Nov 22 12:28:27 2015 Raphael Ghikh
##

CC		=	gcc

NAME		=	push_swap

SRCS		=	my_atoi.c \
			my_putchar.c \
			my_put_nbr.c \
			my_putstr.c \
			main.c \
			push_swap.c \

RM		=	rm -f

all:
	gcc -o $(NAME) $(SRCS)

clean:
	$(RM) $(NAME)

fclean:
	$(RM) $(NAME)

re:
	gcc -o $(NAME) $(SRCS)
	$(RM) $(NAME)
