##
## Makefile for bsq in /home/ghikh_r/ghikh_r/rendu/C_Prog_Elem/CPE_2015_BSQ
## 
## Made by Ghikh
## Login   <ghikh_r@epitech.net>
## 
## Started on  Tue Dec 15 12:01:14 2015 Ghikh
## Last update Sun Dec 20 13:40:59 2015 Ghikh
##

CC		=	gcc -o

SRCS		=	structure_bsq.c \
			structure.h \
			functions.c \

NAME		=	bsq

RM		=	rm -f

all:	$(NAME)

$(NAME):
	$(CC) $(NAME) $(SRCS)

clean:
	$(RM) $(NAME)

fclean:
	$(RM) $(NAME)

re:
	$(RM) $(NAME)
	$(CC) $(NAME) $(SRCS)
